lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser_common do
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:put_secure_browser_headers)
    plug(CodeStatsWeb.RememberMePlug)
    plug(CodeStatsWeb.SetSessionUserPlug)
    plug(CodeStatsWeb.ConsentPlug)
  end

  pipeline :browser_html do
    plug(:accepts, ["html"])
  end

  pipeline :browser_csv do
    plug(:accepts, ["csv"])
  end

  pipeline :browser_auth do
    plug(CodeStatsWeb.AuthRequiredPlug)
  end

  pipeline :browser_unauth do
    plug(CodeStatsWeb.AuthNotAllowedPlug)
  end

  pipeline :browser_changes_state do
    plug(:protect_from_forgery)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :browser_api do
    plug(:fetch_session)
    plug(CodeStatsWeb.SetSessionUserPlug)
  end

  pipeline :api_machine_auth do
    plug(CodeStatsWeb.MachineAuthRequiredPlug)
  end

  scope "/" do
    pipe_through(:browser_html)
    pipe_through(:browser_common)

    get("/", CodeStatsWeb.PageController, :index)

    get("/api-docs", CodeStatsWeb.PageController, :api_docs)
    get("/tos", CodeStatsWeb.PageController, :terms)
    get("/plugins", CodeStatsWeb.PageController, :plugins)
    get("/changes", CodeStatsWeb.ChangesController, :changes)
    get("/support", CodeStatsWeb.SupportController, :page)

    get("/aliases", CodeStatsWeb.AliasController, :list)

    get("/battle", CodeStatsWeb.BattleController, :battle)

    scope "/" do
      pipe_through(:browser_changes_state)
      pipe_through(:browser_unauth)

      get("/login", CodeStatsWeb.AuthController, :render_login)
      post("/login", CodeStatsWeb.AuthController, :login)
      get("/signup", CodeStatsWeb.AuthController, :render_signup)
      post("/signup", CodeStatsWeb.AuthController, :signup)
      get("/forgot-password", CodeStatsWeb.AuthController, :render_forgot)
      post("/forgot-password", CodeStatsWeb.AuthController, :forgot)
      get("/reset-password/:token", CodeStatsWeb.AuthController, :render_reset)
      put("/reset-password/:token", CodeStatsWeb.AuthController, :reset)
    end

    get("/logout", CodeStatsWeb.AuthController, :logout)

    get("/users/:username", CodeStatsWeb.ProfileController, :profile)
    get("/users/:username/avatar", CodeStatsWeb.ProfileController, :profile_gravatar)

    scope "/my", CodeStatsWeb do
      pipe_through(:browser_changes_state)
      pipe_through(:browser_auth)

      get("/profile", ProfileController, :my_profile)

      get("/preferences", PreferencesController, :edit)
      put("/preferences", PreferencesController, :do_edit)
      delete("/preferences", PreferencesController, :delete)

      get("/machines", MachineController, :list)
      post("/machines", MachineController, :add)
      get("/machines/:id", MachineController, :view_single)
      put("/machines/:id", MachineController, :edit)
      delete("/machines/:id", MachineController, :delete)
      post("/machines/:id/activate", MachineController, :activate)
      post("/machines/:id/deactivate", MachineController, :deactivate)
      post("/machines/:id/key", MachineController, :regen_machine_key)

      get("/consent", TermsController, :ask_consent)
      post("/consent", TermsController, :set_consent)
      delete("/consent-delete", TermsController, :delete_account)
    end
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_csv)
    pipe_through(:browser_common)
    pipe_through(:browser_auth)

    get("/my/pulses", PulseController, :list)
    get("/my/private", ProfileController, :export_private)
  end

  scope "/" do
    pipe_through(:api)
    pipe_through(:browser_api)

    forward("/profile-graph", Absinthe.Plug, schema: CodeStats.Profile.PublicSchema)
    forward("/profile-graphiql", Absinthe.Plug.GraphiQL, schema: CodeStats.Profile.PublicSchema)
  end

  scope "/api", CodeStatsWeb do
    pipe_through(:api)

    get("/users/:username", ProfileController, :profile_api)

    scope "/my" do
      pipe_through(:api_machine_auth)

      post("/pulses", PulseController, :add)
    end
  end
end

lib/code_stats_web/controllers/preferences_controller.ex
defmodule CodeStatsWeb.PreferencesController do
  use CodeStatsWeb, :controller

  alias CodeStats.User
  alias CodeStats.User.Alias
  alias CodeStatsWeb.AuthUtils

  require Logger

  plug(:set_title)

  @spec edit(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def edit(conn, _params) do
    conn
    |> common_edit_assigns()
    |> render("preferences.html")
  end

  @doc """
  Common action for all editing calls: currently preferences and passwords.

  The body is chosen by the given hidden field.
  """
  @spec do_edit(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def do_edit(conn, params)

  # Edit case for editing user's information (w/o password)
  def do_edit(conn, %{"user" => %{"type" => "edit"} = user}) do
    changeset = User.updating_changeset(AuthUtils.get_current_user(conn), user)

    case AuthUtils.update_user(changeset) do
      %User{} ->
        conn
        |> put_flash(:success, "Preferences updated!")
        |> redirect(to: Routes.preferences_path(conn, :edit))

      %Ecto.Changeset{} = error_changeset ->
        conn
        |> common_edit_assigns()
        |> put_flash(:error, "Error updating preferences.")
        |> render("preferences.html", changeset: error_changeset)
    end
  end

  # Edit case for editing user's password
  def do_edit(conn, %{
        "user" =>
          %{
            "type" => "password",
            "old_password" => old_password,
            "password" => _
          } = params
      }) do
    user = AuthUtils.get_current_user(conn)
    password_changeset = User.password_changeset(user, params)

    with {:old_pass, true} <- {:old_pass, AuthUtils.check_user_password(user, old_password)},
         {:updated, %User{}} <- {:updated, AuthUtils.update_user(password_changeset)} do
      conn
      |> put_flash(:success, "Password changed.")
      |> redirect(to: Routes.preferences_path(conn, :edit))
    else
      err ->
        error_changeset = get_password_error_cset(err, password_changeset)

        conn
        |> common_edit_assigns()
        |> put_flash(:error, "Error changing password.")
        |> render("preferences.html", pass_changeset: error_changeset)
    end
  end

  # Edit case for editing user's aliases
  def do_edit(conn, %{"user" => %{"type" => "aliases"}, "aliases" => data}) do
    with {:json, {:ok, aliases}} <- {:json, Jason.decode(data)},
         {:validate, %Ecto.Changeset{valid?: true} = changeset} <-
           {:validate,
            User.aliases_changeset(AuthUtils.get_current_user(conn), %{aliases: aliases})},
         {:save, %User{} = user} <- {:save, AuthUtils.update_user(changeset)} do
      :ok = User.update_aliases(user)
      Task.start(fn -> User.CacheUtils.update_all!(user) end)

      put_flash(
        conn,
        :success,
        "Aliases updated. It may take a while for the change to be reflected in your profile."
      )
      |> redirect(to: Routes.preferences_path(conn, :edit))
    else
      {:json, _} ->
        put_flash(conn, :error, "Invalid JSON input.")

      {phase, changeset} when phase in [:validate, :save] ->
        conn
        |> put_flash(:error, "Error setting aliases.")
        |> common_edit_assigns()
        |> assign(:aliases_json, data)
        |> assign(:aliases_changeset, changeset)
        |> render("preferences.html")
    end
  end

  # Edit case for any other data, just return an error.
  def do_edit(conn, _params) do
    conn
    |> common_edit_assigns()
    |> put_flash(:error, "Unknown error in preferences.")
    |> render("preferences.html")
  end

  @doc """
  Action for deleting user and all their information from system.
  """
  @spec delete(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def delete(conn, params) do
    AuthUtils.delete_user_action(conn, params, {&Routes.preferences_path/2, :edit})
  end

  defp get_password_error_cset({:old_pass, false}, orig_changeset) do
    # We need to add an action to the changeset so that Phoenix will display the error,
    # otherwise it will think the changeset was not processed (as it has not been passed
    # to any Repo call) and will not show the errors
    %{orig_changeset | action: :update}
    |> Ecto.Changeset.add_error(:old_password, "does not match your current password")
  end

  defp get_password_error_cset({:updated, cset}, _), do: cset

  # Common edit assigns, including empty changesets that will be overridden in specific clauses
  defp common_edit_assigns(conn) do
    user_data = AuthUtils.get_current_user(conn)

    alias_data =
      user_data.aliases
      |> Alias.preload_languages()
      |> aliases_as_json()

    conn
    |> assign(:user, user_data)
    |> assign(:changeset, User.updating_changeset(user_data))
    |> assign(:pass_changeset, User.password_changeset(user_data))
    |> assign(:aliases_changeset, User.aliases_changeset(user_data))
    |> assign(:aliases_json, alias_data)
  end

  defp set_title(conn, _opts) do
    assign(conn, :title, "Preferences")
  end

  @spec aliases_as_json([Alias.t()]) :: String.t()
  defp aliases_as_json(aliases) do
    aliases
    |> Enum.map(fn
      alias when not is_nil(alias.target) ->
        %{"source" => alias.source.name, "target" => alias.target.name}

      alias ->
        %{"source" => alias.source.name, "target" => nil}
    end)
    |> Jason.encode!()
  end
end

lib/code_stats_web/views/preferences_view.ex
defmodule CodeStatsWeb.PreferencesView do
  use CodeStatsWeb, :view

  def get_flash(conn, type), do: CodeStatsWeb.LayoutView.get_flash(conn, type)
end

lib/code_stats_web/templates/preferences/preferences.html.eex
<div id="preferences-stripe" class="stripe">
  <h1>Preferences</h1>

  <div id="tab-container"></div>

  <div id="preferences-container">
    <div id="user-details">
      <h2>User details</h2>

      <%= form_for(@changeset, Routes.preferences_path(@conn, :do_edit), fn f -> %>
        <%= hidden_input(f, :type, value: "edit", id: "edit-type") %>

        <%= label(f, :email, "Email address") %>
        <div class="input">
          <%= email_input(f, :email, minlength: 3, maxlength: 255) %>
          <%= error_tag(f, :email) %>
          <p class="help-block">
            Email is only used for important notifications about the service, not for promotions or spam.
          </p>
        </div>

        <%= label(f, :private_profile, "Private profile") %>
        <div class="input">
          <%= checkbox(f, :private_profile) %>

          <p class="help-block">
            Private profile can only be seen by yourself.
          </p>
        </div>

        <%= label(f, :gravatar_email, "Gravatar email") %>
        <div class="input">
          <%= email_input(f, :gravatar_email, minlength: 3, maxlength: 255) %>
          <%= error_tag(f, :gravatar_email) %>
          <p class="help-block">
            Email to use for displaying Gravatar. Can be the same or different as your main email. Email or its hash is not revealed to viewers.
          </p>
        </div>

        <div class="submit"><%= submit("Update preferences") %></div>
      <% end) %>
    </div>

    <div id="user-aliases">
      <h2>Language aliases</h2>

      <p>
        With this editor, you can configure user level language aliases. A language alias means that XP coming in with one language name is shown under another name in your profile. Aliases are case insensitive.
      </p>

      <p>
        Note that in addition to your own aliases, the service has global aliases that apply to all users. You can override those aliases too using this editor.
        <a href="<%= Routes.alias_path(@conn, :list) %>" target="_blank">See list of global aliases.</a>
      </p>

      <p>Please <a href="#aliases-help">read the help</a> before using the editor.</p>

      <%= form_for(@aliases_changeset, Routes.preferences_path(@conn, :do_edit), [class: "no-form-style", id: "aliases-editor-form" ], fn f -> %>
        <%= hidden_input(f, :type, value: "aliases", id: "edit-type") %>

        <%= for change <- Map.get(f.source.changes, :aliases, []) do %>
          <%= if not change.valid? do %>
            <p class="has-error">
              Alias from "<%= change.changes[:source] %>" to "<%= change.changes[:target] %>" has the following issues:
            </p>

            <ul class="has-error">
              <%= if change.errors[:source] do %>
                <li>Source: <%= translate_error(change.errors[:source]) %></li>
              <% end %>
              <%= if change.errors[:target] do %>
                <li>Target: <%= translate_error(change.errors[:target]) %></li>
              <% end %>
            </ul>
          <% end %>
        <% end %>

        <div id="aliases-editor">
          <textarea name="aliases" id="aliases">
            <%= @aliases_json %>
          </textarea>

          <div id="aliases-submit">
            <%= submit("Update aliases", id: "aliases-submit") %>
          </div>
        </div>
      <% end) %>

      <h3 id="aliases-help">Alias editor help</h3>

      <p>
        <ul>
          <li>An empty name in the target field will result in the language being hidden in your profile and its XP being removed from all your statistics.</li>
          <li>Aliases are case insensitive, so you cannot change only the casing of a language with this editor. If you need to do that, please contact the administrators.</li>
          <li>Aliases are not processed recursively, so a chain A → B, B → C will not lead to A → C.</li>
          <li>Any changes will require a reprocessing of the profile's XP cache, so it may take a moment before changes are seen on the profile page.</li>
          <li>Click on an alias name in the "Current data" tables to copy it to the clipboard.</li>
          <li>All changes are always reversible by undoing the aliases and saving.</li>
        </ul>
      </p>
    </div>

    <div id="change-password">
      <h2>Change password</h2>

      <%= form_for(@pass_changeset, Routes.preferences_path(@conn, :do_edit), fn f -> %>
        <%= hidden_input(f, :type, value: "password", id: "password-type") %>

        <%= label(f, :old_password, "Current password (required)") %>
        <div class="input">
          <%= password_input(f, :old_password, autocomplete: "current-password", required: true) %>
          <%= error_tag(f, :old_password) %>
          <p class="help-block">
            For security, to change your password, you need to also give your current password.
          </p>
        </div>

        <%= label(f, :password, "New password (required)") %>
        <div class="input">
          <%= password_input(f, :password, autocomplete: "new-password", required: true, minlength: 6) %>
          <%= error_tag(f, :password) %>
        </div>

        <div class="submit"><button type="submit">Change password</button></div>
      <% end) %>
    </div>

    <div id="export-data">
      <h2>Export data</h2>

      <div id="export-data-container">
        <p>
          Press the button below to download your XP data in CSV format. You can also include all
          private data contained in the service about your account. See the
          <a href="<%= Routes.page_path(@conn, :terms) %>">privacy policy</a> for more information.
        </p>

        <form>
          <label for="include-private-data">Include private data in CSV export</label>
          <input type="checkbox" id="include-private-data">

          <div class="submit">
            <button id="export-data-button" type="button">Download data</button>
          </div>
        </form>
      </div>

      <div id="export-data-processing"></div>
    </div>

    <div id="delete-account">
      <h2>Delete account</h2>

      <p>
        If you wish to delete your account, please input "DELETE" into the field below and press
        the delete button. If you do this, all your data will be removed and cannot be recovered.
      </p>

      <%= form_tag(Routes.preferences_path(@conn, :do_edit), method: :delete) %>
        <label><strong>This cannot be undone!</strong></label>
        <input type="text" class="form-control" name="delete_confirmation" maxlength="6" required />

        <div class="submit"><button type="submit" class="button-danger">Delete account forever</button></div>
      </form>
    </div>
  </div>
</div>